on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

permissions:
  contents: write

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.10
        with:
          version: 10.27.0

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: pnpm

      - name: Clean install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm build

      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
        with:
          html_path: ./dist/angular-compiler-output/browser/index.html
          base_href: /angular-compiler-output/

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/angular-compiler-output/browser
